import { Document } from "mongoose";

export default interface userInterface extends Document{
    name:{
        type:string,
        required:true
    },
    age:{
        type:number,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    password:{
        type:String,
        required:true
    },
    salt:{
        type:String, 
        required:true
    }
    indentification:{
        type:Object,
        required:true
    },
    description:{
        type:String,
        required:true
    },
    avatar:{
        type:string,
        required:false
    },
    field:{
        isAdmin:{
            type:boolean,
            required:false
        },
        isSalesman:{
            type:boolean,
            required:false
        },
        isBuyer:{
            type:Boolean,
            required:false
        }
    },
    endereco:[{
        city:{
            type:String,
            required:false
        },
        state:{
            type:String,
            required:false
        },
        street:{
            type:String,
            required:false
        },
        neighborhood:{
            type:String,
            required:false
        },
        cep:{
            type:String,
            required:false
        }
    }]
}

  